[package]
version = "1.0.0" # Semantic Versioning is used: https://semver.org/

# These fields are used primarily for display in the extension browser UI.
authors = ["David Bosnich <dbosnich@nvidia.com>"]
title = "Example C++ Extension: pybind"
description = "An example C++ extension."
category = "Example"
keywords = ["example"]
changelog = "docs/CHANGELOG.md"
readme  = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"
repository = "https://github.com/NVIDIA-Omniverse/kit-extension-template-cpp"

# Define the Python modules that this extension provides.
[[python.module]]
name = "omni.example.cpp.pybind"

# Define the C++ plugins that this extension provides.
[[native.plugin]]
path = "bin/*.plugin"
