[package]
version = "1.0.0" # Semantic Versioning is used: https://semver.org/

# These fields are used primarily for display in the extension browser UI.
title = "Example C++ Extension: pybind"
description = "Demonstrates how to reflect C++ code using pybind11 so that it can be called from Python code."
category = "Example"
keywords = ["example", "C++", "cpp", "pybind"]
icon = "data/icon.png"
preview_image = "data/preview.png"
changelog = "docs/CHANGELOG.md"
readme  = "docs/README.md"
authors = ["David Bosnich <dbosnich@nvidia.com>"]
repository = "https://github.com/NVIDIA-Omniverse/kit-extension-template-cpp"

# Define the Python modules that this extension provides.
[[python.module]]
name = "omni.example.cpp.pybind"

# Define the C++ plugins that this extension provides.
[[native.plugin]]
path = "bin/*.plugin"

[documentation]
pages = [
    "docs/Overview.md",
    "docs/CHANGELOG.md",
]
cpp_api = [
     "include/omni/example/cpp/pybind/IExampleBoundInterface.h",
     "include/omni/example/cpp/pybind/IExampleBoundObject.h",
     "include/omni/example/cpp/pybind/ExampleBoundObject.h",
]
